export default function FAQ() {
  const faqs = [
    {
      q: "What does Tidy check?",
      a: "Tidy checks 11 data points per product: title, description, images, image alt text, SEO title, SEO description, product category, product type, tags, barcodes, and vendor. Each missing or incomplete field lowers the product's health score.",
    },
    {
      q: "Does Tidy change anything in my store automatically?",
      a: "No. Tidy only reads your product data during a scan. When you use AI fixes, you always see a preview of the generated content before anything is applied. Nothing changes until you click 'Apply'.",
    },
    {
      q: "What AI model do you use?",
      a: "Tidy uses OpenAI's GPT-4o-mini for generating descriptions, SEO metadata, alt text, and tags. Product titles and descriptions are sent to OpenAI when you request a fix. Images are sent only for alt text generation.",
    },
    {
      q: "Can I generate content in my language?",
      a: "Yes. Go to Settings and select your content language. Tidy supports 28 languages. All AI-generated content will be written in your selected language.",
    },
    {
      q: "How long does a scan take?",
      a: "Usually under a minute, even for stores with hundreds of products. Tidy uses Shopify's Bulk Operations API to fetch all products at once.",
    },
    {
      q: "What happens when I uninstall Tidy?",
      a: "All your data is permanently deleted from our servers - scan results, settings, and sessions. Nothing remains. Your Shopify products are not affected.",
    },
    {
      q: "Why are some issues marked as 'not fixable'?",
      a: "Barcodes and vendor information can't be generated by AI because they're factual data specific to your products. You'll need to add those manually in Shopify admin.",
    },
    {
      q: "Does Tidy help with Google Merchant Center?",
      a: "Yes. Missing product categories, GTINs/barcodes, and incomplete descriptions are common reasons Google disapproves products. Tidy identifies all of these and can fix the ones that AI can help with.",
    },
    {
      q: "How is the health score calculated?",
      a: "Each of the 11 data points has a weight. Critical fields like alt text and descriptions count more than optional fields like tags. A product with everything filled in scores 100. Missing fields subtract from the score based on their weight.",
    },
    {
      q: "Can I scan specific products instead of all of them?",
      a: "Currently Tidy scans your entire catalog at once. After fixing a product, it's automatically rescanned so the score updates immediately.",
    },
  ];

  return (
    <div style={{ maxWidth: 720, margin: "0 auto", padding: "3rem 1.5rem", fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", color: "#3d3d3d", lineHeight: 1.7 }}>
      <h1 style={{ fontSize: "1.8rem", fontWeight: 700, marginBottom: "2rem" }}>Frequently Asked Questions</h1>

      {faqs.map((faq, i) => (
        <div key={i} style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.1rem", fontWeight: 600, marginBottom: "0.3rem" }}>{faq.q}</h2>
          <p style={{ color: "#555" }}>{faq.a}</p>
        </div>
      ))}

      <div style={{ borderTop: "1px solid #eee", paddingTop: "1.5rem", marginTop: "1rem" }}>
        <p style={{ color: "#888" }}>
          Have another question? Email us at{" "}
          <a href="mailto:tidy@emre.zip" style={{ color: "#c49a3c" }}>tidy@emre.zip</a>
        </p>
      </div>
    </div>
  );
}
